### PR TITLE
classNames -> classList

### PR DESCRIPTION
**Pull request by mninc**
at some point html.parser must have changed classNames to classList. operations using this do not succeed (TypeError: argument of type 'NoneType' is not iterable - var.classNames is None rather than a list). this fixes that

### CODE REVIEW

**Comment by kata198** [comment]
Can you please provide a testcase which shows this error? The entire unit test suite passes on python 2.7 and python 3.4, 3.5, 3.6, and 3.7.

Some sample html and code you are using. Thanks!

**Comment by kata198** [comment]
Please check out 8.1 branch and try again, I believe I have fixed the issue with 1 line. 

If you still can identify an issue, please post how to trigger. Thanks.

**Comment by mninc** [comment]
yeah, that works

**Comment by kata198** [comment]
Awesome! Thanks so much for testing.

Would you like your real name to go in the Changelog for this issue or is "mninc on github.com" your preferred credit?

**Comment by mninc** [comment]
The second one is fine.

**Pull request closed without merging**
